spring:
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    baseline-description: Flyway Scripts
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#    url: ${spring.datasource.url}
#    default-schema: carshop
#    out-of-order: true
#    ignore-migration-patterns: '*:ignored'
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/jd2"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/jd2"
server:
  port: 8080

#  baa82fe9-471b-45bb-98e3-1c882fcc4f4f