spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: cars_rent
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/carsrent"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/carsrent"
#  mail:
#    host: "smtp.gmail.com"
#    port: 587
#    username: logonukapi@gmail.com
#    password: ziqmivhxddfrugme
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
server:
  port: 8080

---

jwt:
  secret: sdfsdfwejfwiofjnoldivcow2371984
  expiration: 60000